apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.sql_db_name }}
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.data_base_root_pass }}
        - name: MYSQL_DATABASE
          value: {{ .Values.data_base_name }}
        - name: MYSQL_USER
          value: {{ .Values.user }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.data_base_pass }}
        name: {{ .Values.sql_db_name }}
        image: {{ .Values.sql_image }}
