apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.wordpress }}
  labels:
    app: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: {{ .Values.wordpress }}
        image: {{ .Values.wordpress_image }}
        ports:
        - containerPort: 80
